#ifndef NANOS_LITE_FS_FAT32_H
#define NANOS_LITE_FS_FAT32_H

#include <stddef.h>
#include <stdint.h>

#define FAT32_ATTR_READ_ONLY 0x01u
#define FAT32_ATTR_HIDDEN 0x02u
#define FAT32_ATTR_SYSTEM 0x04u
#define FAT32_ATTR_VOLUME_ID 0x08u
#define FAT32_ATTR_DIRECTORY 0x10u
#define FAT32_ATTR_ARCHIVE 0x20u
#define FAT32_ATTR_LONG_NAME (FAT32_ATTR_READ_ONLY | FAT32_ATTR_HIDDEN | FAT32_ATTR_SYSTEM | FAT32_ATTR_VOLUME_ID)

/*
 * One 32-byte FAT long-file-name slot, stored immediately before the matching
 * short 8.3 directory entry.  The Microsoft FAT specification names these
 * fields LDIR_Ord, LDIR_Name1, LDIR_Attr, LDIR_Type, LDIR_Chksum,
 * LDIR_Name2, LDIR_FstClusLO, and LDIR_Name3.  The structure is packed because
 * it overlays raw on-disk bytes; adding compiler padding would move the UTF-16
 * character fields away from their specified offsets.
 */
typedef struct __attribute__((packed))
{
    /*
   * Sequence number in the low five bits.  Bit 6 marks the last logical piece,
   * which appears first on disk because FAT stores long-name pieces in reverse
   * order before the short entry.
   */
    uint8_t order;
    /* First five UTF-16LE code units from this 13-character LFN fragment. */
    uint16_t name1[5];
    /* Must be FAT32_ATTR_LONG_NAME (0x0f), identifying this as an LFN slot. */
    uint8_t attr;
    /* Must be zero for normal FAT long-name entries. */
    uint8_t type;
    /*
   * Checksum of the following short 8.3 name.  It binds the LFN pieces to the
   * short entry so a stale or reordered long-name chain is ignored.
   */
    uint8_t checksum;
    /* Middle six UTF-16LE code units from this LFN fragment. */
    uint16_t name2[6];
    /* Must be zero; LFN entries do not own clusters. */
    uint16_t first_cluster_low;
    /* Final two UTF-16LE code units from this LFN fragment. */
    uint16_t name3[2];
} Fat32LfnEntry;

/*
 * Mounted FAT32 volume geometry and small caches derived from the BPB, FSInfo,
 * and FAT.  All sector counts are expressed in 512-byte sectors because this
 * Nanos-lite driver intentionally supports only the 512-byte-sector FAT32
 * images generated by navy-apps/scripts/mkfat32.py.
 */
typedef struct
{
    /*
   * BPB_BytsPerSec.  The FAT spec allows 512, 1024, 2048, or 4096, but this
   * driver accepts only 512 so disk offsets and test images stay simple.
   */
    uint16_t bytes_per_sector;
    /*
   * BPB_SecPerClus.  A cluster is the allocation unit named by FAT entries; the
   * spec requires this to be a non-zero power of two.
   */
    uint8_t sectors_per_cluster;
    /*
   * BPB_RsvdSecCnt.  Sectors before the first FAT, including the boot sector,
   * FSInfo sector, and backup boot/FSInfo sectors.
   */
    uint16_t reserved_sector_count;
    /*
   * BPB_NumFATs.  Usually 2.  When mirroring is enabled, writes update every
   * FAT copy; otherwise active_fat selects the only copy to use.
   */
    uint8_t fat_count;
    /* BPB_TotSec32.  Total sectors in the whole FAT32 image. */
    uint32_t total_sectors;
    /* BPB_FATSz32.  Sector count occupied by one FAT copy. */
    uint32_t fat_size_sectors;
    /*
   * BPB_ExtFlags.  Bit 7 controls FAT mirroring; low four bits select the
   * active FAT when mirroring is disabled.
   */
    uint16_t ext_flags;
    /* True when all FAT copies should be kept in sync. */
    uint8_t mirror_fats;
    /* Active FAT index from BPB_ExtFlags when mirroring is disabled, else 0. */
    uint8_t active_fat;
    /*
   * BPB_RootClus.  First cluster of the FAT32 root directory.  Unlike FAT12/16,
   * FAT32 has no fixed root directory region.
   */
    uint32_t root_cluster;
    /* BPB_FSInfo.  Reserved-sector index of the primary FSInfo structure. */
    uint16_t fsinfo_sector;
    /*
   * BPB_BkBootSec.  Sector containing the backup boot record; the backup FSInfo
   * copy is found at backup_boot_sector + fsinfo_sector.
   */
    uint16_t backup_boot_sector;
    /*
   * Computed first data-sector number:
   * reserved_sector_count + fat_count * fat_size_sectors.
   */
    uint32_t first_data_sector;
    /* Number of sectors in the cluster-addressable data area. */
    uint32_t data_sectors;
    /*
   * CountOfClusters from the FAT spec.  This decides FAT type at mount time;
   * FAT32 requires at least 65525 clusters.
   */
    uint32_t cluster_count;
    /* True only after FSInfo signatures have been validated. */
    uint8_t fsinfo_valid;
    /*
   * FSI_Free_Count.  Advisory free-cluster count; 0xffffffff means unknown, so
   * allocation still validates actual FAT entries before using a cluster.
   */
    uint32_t free_cluster_count;
    /*
   * FSI_Nxt_Free.  Advisory starting point for allocation scans.  It is useful
   * for speed but cannot be trusted without checking the FAT entry itself.
   */
    uint32_t next_free_cluster;
    /* True when fat_sector_cache contains a valid FAT sector. */
    uint8_t fat_sector_cache_valid;
    /* FAT copy index represented by fat_sector_cache. */
    uint8_t fat_sector_cache_fat_index;
    /* Absolute byte offset in the disk image for the cached FAT sector. */
    uint64_t fat_sector_cache_offset;
    /*
   * One 512-byte FAT sector cache.  FAT32 entries are four bytes and never span
   * a sector boundary, so this holds up to 128 adjacent FAT entries.
   */
    uint8_t fat_sector_cache[512];
} Fat32Volume;

/*
 * Result of one directory lookup.  It mirrors the useful pieces of the 32-byte
 * short directory entry; long-name entries only help locate this final entry.
 */
typedef struct
{
    /* Raw DIR_Attr byte for read-only, directory, archive, and related flags. */
    uint8_t attr;
    /* First cluster from DIR_FstClusHI:DIR_FstClusLO, or zero for empty files. */
    uint32_t first_cluster;
    /* DIR_FileSize in bytes.  For directories the FAT spec requires this to be 0. */
    uint32_t size;
    /*
   * Absolute byte offset of the short entry.  Write support needs this so size
   * and first-cluster fields can be written back after allocation changes.
   */
    uint64_t dir_entry_offset;
} Fat32DirEntry;

/*
 * Mutable state for an opened FAT32 regular file.  This is copied into the
 * backend-neutral FsFile descriptor slot and copied back after each operation.
 */
typedef struct
{
    /* Raw DIR_Attr byte; read-only files reject writes and truncates. */
    uint8_t attr;
    /* First data cluster, or zero while an empty file has no allocated chain. */
    uint32_t first_cluster;
    /* Logical byte length from DIR_FileSize, updated after extending writes. */
    uint32_t size;
    /* Absolute byte offset of the short directory entry for metadata updates. */
    uint64_t dir_entry_offset;
    /* File-relative cluster index represented by cached_cluster. */
    uint32_t cached_cluster_index;
    /* FAT cluster number at cached_cluster_index. */
    uint32_t cached_cluster;
    /*
   * Verified contiguous prefix length from first_cluster.  This never assumes
   * contiguity from the builder; it grows only after FAT links have been read.
   */
    uint32_t contiguous_cluster_count;
} Fat32File;

uint8_t fat32_lfn_checksum(const uint8_t short_name[11]);
int fat32_lfn_entry_to_ascii(const Fat32LfnEntry *entry, char *out, size_t out_size);
int fat32_parse_bpb(const uint8_t sector[512], uint32_t disk_block_size, Fat32Volume *out);
int fat32_mount_from_disk(uint32_t disk_block_size, Fat32Volume *out);
int fat32_first_sector_of_cluster(const Fat32Volume *vol, uint32_t cluster, uint32_t *out_sector);
int fat32_is_end_of_chain(uint32_t value);
int fat32_is_bad_cluster(uint32_t value);
int fat32_read_fat_entry(const Fat32Volume *vol, uint32_t cluster, uint32_t *next_cluster);
int fat32_write_fat_entry(const Fat32Volume *vol, uint32_t cluster, uint32_t value);
int fat32_load_fsinfo(Fat32Volume *vol);
int fat32_flush_fsinfo(const Fat32Volume *vol);
int fat32_alloc_cluster(Fat32Volume *vol, uint32_t preferred_after, uint32_t *out_cluster);
int fat32_free_chain(Fat32Volume *vol, uint32_t first_cluster);
int fat32_lookup_path(const Fat32Volume *vol, const char *path, Fat32DirEntry *out);
int fat32_backend_init(void);
int fat32_backend_open(const char *path, Fat32File *out);
size_t fat32_backend_read(Fat32File *file, size_t offset, void *buf, size_t len);
size_t fat32_backend_write(Fat32File *file, size_t offset, const void *buf, size_t len);
size_t fat32_backend_size(const Fat32File *file);
int fat32_backend_truncate(Fat32File *file, uint32_t size);
int fat32_backend_close(Fat32File *file);

#ifdef FAT32_HOST_TEST
void fat32_test_fill_lfn_entry(Fat32LfnEntry *entry, const uint16_t chars[13]);
void fat32_test_reset_backend(void);
#endif

#endif
