#include <cpu/decode.h>
#include "../local-include/rtl.h"

#define INSTR_LIST(f) \
    f(lui) \
    f(lb) \
    f(lh) \
    f(lw) \
    f(ld) \
    f(lbu) \
    f(lhu) \
    f(lwu) \
    f(sb) \
    f(sh) \
    f(sw) \
    f(sd) \
    f(addi) \
    f(slli) \
    f(srli) \
    f(srai) \
    f(slti) \
    f(sltiu) \
    f(xori) \
    f(ori) \
    f(andi) \
    f(addiw) \
    f(slliw) \
    f(srliw) \
    f(sraiw) \
    f(auipc) \
    f(add) \
    f(sub) \
    f(sll) \
    f(slt) \
    f(sltu) \
    f(xor) \
    f(srl) \
    f(sra) \
    f(or) \
    f(and) \
    f(addw) \
    f(subw) \
    f(sllw) \
    f(srlw) \
    f(sraw) \
    f(mul) \
    f(mulh) \
    f(mulhsu) \
    f(mulhu) \
    f(div) \
    f(divu) \
    f(rem) \
    f(remu) \
    f(mulw) \
    f(divw) \
    f(divuw) \
    f(remw) \
    f(remuw) \
    f(beq) \
    f(bne) \
    f(blt) \
    f(bge) \
    f(bltu) \
    f(bgeu) \
    f(jal) \
    f(jalr) \
    f(csrrw) \
    f(csrrs) \
    f(csrrc) \
    f(csrrwi) \
    f(csrrsi) \
    f(csrrci) \
    f(ecall) \
    f(ebreak) \
    f(mret) \
    f(sfence_vma) \
    f(fence) \
    f(fence_i) \
    f(wfi) \
    f(inv) \
    f(nemu_trap)

def_all_EXEC_ID();
